# Generated by Django 5.0.1 on 2024-01-13 11:01

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('delete_object', django.db.models.manager.Manager()),
            ],
        ),
    ]
