# Generated by Django 5.0.1 on 2024-01-13 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_like_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='amount',
        ),
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
